#!/usr/bin/env python
# -*- coding: utf-8 -*-
input_first=input()
first = []
for ki in range(3):
    first = input_first.rstrip().split(' ')
a = first[0]
b = first[1]
n = first[2]
input_second=input()
for pi in range(len(input_second)):
    p = input_second.rstrip().split(' ')
q = []
for i in range(0,int(a)):
    if p[2*i] == b:
        p.insert(2*i+1,"0")
    elif p[2*i+1] == "G":
        p[2*i+1] = "0"
    elif p[2*i] == "G":
        p[2*i] = "0"
    else:
        pass
point = 0
for j in range(len(p)//2):
    if int(p[2*j]) == int(b):
        if int(p[2*j+2]) == int(b):
            point += 2*int(b) + int(p[2*j+4])
        else:
            point += int(b) +int(p[2*j+2]) + int(p[2*j+3])
    elif int(p[2*j+1]) + int(p[2*j]) == int(b):
        point += int(b) + int(p[2*j+2])
    else:
        point += int(p[2*j]) + int(p[2*j+1])
if len(p) % 2 == 0:
    pass
else:
    point = point + int(p[-1])
print(point)
