#!/usr/bin/env python
# -*- coding: utf-8 -*-
import random
import matplotlib.pyplot as plt
import math 
import numpy as np
n = input()
num = [[0] * 2] * (int(n))
crs = [[0] * 2] * (3)
com = [[0] * 3] * (int(n))
for i in range(int(n)):
    x = np.random.randn()
    y = np.random.randn()
    num[i][0] = x
    num[i][1] = y
    plt.plot(x, y, "o", color = "red")
for j in range(3):
    x = np.random.randn()
    y = np.random.randn()
    crs[j][0] = x
    crs[j][1] = y
    plt.plot(x, y, "ro", color = "blue")
print(num)
for k in range(int(n)):
    for l in range(3):
        com[k][l] = math.sqrt((num[k][0]-crs[l][0])**2 + (num[k][1]-crs[l][1])**2)
print(com)
plt.show()
